LINKVALIDATIONS="https://raw.githubusercontent.com/nkzr4/nk-dots/refs/heads/main/arch-setup/validations.sh"
LINKLOGS="https://raw.githubusercontent.com/nkzr4/nk-dots/refs/heads/main/arch-setup/logs.sh"
LINKCHROOT="https://raw.githubusercontent.com/nkzr4/nk-dots/refs/heads/main/arch-setup/chroot-setup.sh"
LINKHYPRCONF="https://raw.githubusercontent.com/nkzr4/nk-dots/refs/heads/main/arch-setup/hyprland.conf.default"
LINKFIRSTINIT="https://raw.githubusercontent.com/nkzr4/nk-dots/refs/heads/main/arch-setup/first-init.sh"
